# . is a special character and cannot appear between field names, spec names etc.
spec.ISO8583.1100.Message Type=fixed.ascii.size:4
spec.ISO8583.1100.Bitmap=bitmap.binary
spec.ISO8583.1100.Bitmap.2.Fixed ASCII=fixed.ascii.size:3
spec.ISO8583.1100.Bitmap.3.Fixed EBCDIC=fixed.ebcdic.size:3
spec.ISO8583.1100.Bitmap.4.Fixed BCD=fixed.bcd.size:3
spec.ISO8583.1100.Bitmap.5.Fixed BINARY=fixed.binary.size:3
spec.ISO8583.1100.Bitmap.55.Var BCD/BINARY=variable.bcd.binary.size:2
spec.ISO8583.1100.Bitmap.56.Var BCD/ASCII=variable.bcd.ascii.size:2
spec.ISO8583.1100.Bitmap.57.Var BINARY/EBCDIC =variable.binary.ebcdic.size:2
spec.ISO8583.1100.Bitmap.58.Var EBCDIC/EBCDIC=variable.ebcdic.ebcdic.size:2
spec.ISO8583.1100.Bitmap.59.Var EBCDIC/ASCII=variable.ebcdic.ascii.size:2
spec.ISO8583.1100.Bitmap.91.Var ASCII/EBCDIC=variable.ascii.ebcdic.size:2.constraints{minSize:0;maxSize:15}
####
####
spec.GCAG.Default.Message Type=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap=bitmap.binary
spec.GCAG.Default.Bitmap.2.PAN=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.3.Processing Code=fixed.ebcdic.size:6
spec.GCAG.Default.Bitmap.4.Transaction Amount=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.5.Transaction, Recon=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.6.Transaction, Cardholder Billing=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.7.Date/Time, Transmission=fixed.ebcdic.size:10
spec.GCAG.Default.Bitmap.11.STAN=fixed.ebcdic.size:6
spec.GCAG.Default.Bitmap.12.Date/Time, Local=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.13.Date Effective=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.14.Date Expiration=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.15.Date Settlement=fixed.ebcdic.size:6
spec.GCAG.Default.Bitmap.16.Date Conversion=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.17.Date Capture=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.18.Merchant Type=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.19.Country Code, Acquiring Institution=fixed.ebcdic.size:3
spec.GCAG.Default.Bitmap.20.Country Code, PAN=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.21.Country Code, Forwarding Institution=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.22.POS Data Code=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.23.Card Sequence No=fixed.ebcdic.size:3
spec.GCAG.Default.Bitmap.24.Function Code=fixed.ebcdic.size:3
spec.GCAG.Default.Bitmap.25.Msg Reason Code=fixed.ebcdic.size:4
spec.GCAG.Default.Bitmap.30.Amounts Original=fixed.ebcdic.size:24
spec.GCAG.Default.Bitmap.31.Acquirer Ref Data=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.32.Acquirer Id Code=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.33.Forwarding Inst Id Code=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.35.Track II=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.37.RRN=fixed.ebcdic.size:12
spec.GCAG.Default.Bitmap.38.Approval Code=fixed.ebcdic.size:6
spec.GCAG.Default.Bitmap.39.Action Code=fixed.ebcdic.size:3
spec.GCAG.Default.Bitmap.41.Card Acceptor Terminal ID=fixed.ebcdic.size:8
spec.GCAG.Default.Bitmap.42.Card Acceptor Id Code=fixed.ebcdic.size:15
spec.GCAG.Default.Bitmap.43.Card Acceptor, Name and Location=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.47.Additional Data, National=variable.ebcdic.ebcdic.size:3
spec.GCAG.Default.Bitmap.49.Currency Code=fixed.ebcdic.size:3
spec.GCAG.Default.Bitmap.52.PIN Data=fixed.binary.size:8
spec.GCAG.Default.Bitmap.53.Security Info Data=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.55.ICC System Related Data=variable.ebcdic.binary.size:3
spec.GCAG.Default.Bitmap.56.Original Elements=variable.ebcdic.ebcdic.size:2
spec.GCAG.Default.Bitmap.64.Message Auth Code (1)=fixed.binary.size:8
spec.GCAG.Default.Bitmap.96.Key Management Data=variable.ebcdic.binary.size:3
spec.GCAG.Default.Bitmap.128.Message Auth Code (2)=fixed.binary.size:8
##
